### ISSUE TITLE
KFC

### ISSUE THREAD

**Issue by samoilovid** [samoilovid/Burger#4]
@coursar, Здравствуйте, у меня проблема в плане пуша 
все началось со вчерашнего дня, я не знаю что пошло не так с этими бургерами, я и репозиторий новый открывал и проект, коммиты каким то образом импортировались, конфликт был, я не знаю как его устранить, сейчас сделал просто под кфс названием, вроде все нормально, но вот это вышло под конец "Push to origin/master was rejected". Помогите пожалуйста.

**Comment by coursar** [comment]
Сделайте `git pull`

**Comment by samoilovid** [comment]
@coursar, From https://github.com/samoilovid/Burger * branch master -> FETCH_HEAD = [up to date] master -> origin/master refusing to merge unrelated histories, истории объединить, можно как-то просто удалить конфликтующие?

**Comment by samoilovid** [comment]
@coursar, 12:03	Git Pull Failed
			POST git-upload-pack (325 bytes)
			remote: Enumerating objects: 9, done.
			remote: Total 9 (delta 0), reused 9 (delta 0), pack-reused 0
			warning: no common commits
			From https://github.com/samoilovid/Burger
			* branch            master     -> FETCH_HEAD
			* [new branch]      master     -> origin/master
			refusing to merge unrelated histories

12:05	Git Pull Failed
			From https://github.com/samoilovid/Burger
			* branch            master     -> FETCH_HEAD
			= [up to date]      master     -> origin/master
			refusing to merge unrelated histories

12:06	Push rejected: Push to origin/master was rejected

**Comment by coursar** [comment]
Вы пытаетесь в этот репо залить другую историю. Пока проще создать новый и залить код туда.
